### ISSUE TITLE
DCA1000EVM USB Connection  not Recognized by Ubuntu 20.04

### ISSUE THREAD

**Issue by orngshrk** [ConnectedSystemsLab/xwr_raw_ros#3]
Hello,

Thank you for creating this repo and publishing it. This code looks like it would solve a problem for research I am involved with. However, I am having some trouble getting it to work. The text printed to the terminal after running radar.launch states that the address was not assigned to the dca and that the RadarPub object is missing the attribute dca1000. I'm sorry I don't have the output saved and on me right now. If necessary, I can go recreate the error and include it, but I may not be able to do so till later this week.

I believe the error is caused because I am apparently unable to connect the DCA1000 through USB and therefore am unable to send the configuration to it. I am using Ubuntu 20.04 with ROS Noetic. When connecting the DCA1000 by USB, my dmesg output shows an FTDI device was connected but it is not assigned a /dev/ttyxxx. I tried installing FTDI drivers (ftdi_sio, ftd2xx), mmWaveSDK, XDS EMUPack, and XDS Support Utilities.

Any help would be greatly appreciated, thank you.

**Comment by sie2** [comment]
If I recall correctly, the USB should not be connected to the DCA1000 but instead the radar dev board. This is because the radar configuration is sent via UART to the dev board, not the DCA1000. 

To check the connection to the radar dev board, you should run `ll /dev/serial/by-id` to see if the radar shows up under `/dev/ttyXXX`. If the connection is working, it should show up as two ports (one for config and one for data).
